//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.12 at 06:16:17 PM MSD 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://spbstu.ru/hello/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.spbstu.telematics.student;
